const ICONS = {
  "500px": {
    unicode: "",
    tags: [],
    style: "brands",
  },
  "address-book": {
    unicode: "",
    tags: [],
    style: "solid",
  },
  "address-card": {
    unicode: "",
    tags: [],
    style: "solid",
  },
  adjust: {
    unicode: "",
    tags: ["contrast"],
    style: "solid",
  },
  algolia: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  amazon: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  "amazon-pay": {
    unicode: "",
    tags: [],
    style: "brands",
  },
  android: {
    unicode: "",
    tags: ["robot"],
    style: "brands",
  },
  "angle-double-down": {
    unicode: "",
    tags: ["arrows"],
    style: "solid",
  },
  "angle-double-left": {
    unicode: "",
    tags: ["laquo", "quote", "previous", "back", "arrows"],
    style: "solid",
  },
  "angle-double-right": {
    unicode: "",
    tags: ["raquo", "quote", "next", "forward", "arrows"],
    style: "solid",
  },
  "angle-double-up": {
    unicode: "",
    tags: ["arrows"],
    style: "solid",
  },
  "angle-down": {
    unicode: "",
    tags: ["arrow"],
    style: "solid",
  },
  "angle-left": {
    unicode: "",
    tags: ["previous", "back", "arrow"],
    style: "solid",
  },
  "angle-right": {
    unicode: "",
    tags: ["next", "forward", "arrow"],
    style: "solid",
  },
  "angle-up": {
    unicode: "",
    tags: ["arrow"],
    style: "solid",
  },
  angular: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  "app-store": {
    unicode: "",
    tags: [],
    style: "brands",
  },
  "app-store-ios": {
    unicode: "",
    tags: [],
    style: "brands",
  },
  apple: {
    unicode: "",
    tags: ["osx", "food"],
    style: "brands",
  },
  "apple-pay": {
    unicode: "",
    tags: [],
    style: "brands",
  },
  archive: {
    unicode: "",
    tags: ["box", "storage", "package"],
    style: "solid",
  },
  "arrow-circle-down": {
    unicode: "",
    tags: ["download"],
    style: "solid",
  },
  "arrow-circle-left": {
    unicode: "",
    tags: ["previous", "back"],
    style: "solid",
  },
  "arrow-circle-right": {
    unicode: "",
    tags: ["next", "forward"],
    style: "solid",
  },
  "arrow-circle-up": {
    unicode: "",
    tags: [],
    style: "solid",
  },
  "arrow-down": {
    unicode: "",
    tags: ["download"],
    style: "solid",
  },
  "arrow-left": {
    unicode: "",
    tags: ["previous", "back"],
    style: "solid",
  },
  "arrow-right": {
    unicode: "",
    tags: ["next", "forward"],
    style: "solid",
  },
  "arrow-up": {
    unicode: "",
    tags: [],
    style: "solid",
  },
  "arrows-alt": {
    unicode: "",
    tags: [
      "expand",
      "enlarge",
      "fullscreen",
      "bigger",
      "move",
      "reorder",
      "resize",
      "arrow",
      "arrows",
    ],
    style: "solid",
  },
  "arrows-alt-h": {
    unicode: "",
    tags: ["resize", "arrows-h"],
    style: "solid",
  },
  "arrows-alt-v": {
    unicode: "",
    tags: ["resize", "arrows-v"],
    style: "solid",
  },
  aws: {
    unicode: "",
    tags: ["amazon web services"],
    style: "brands",
  },
  backward: {
    unicode: "",
    tags: ["rewind", "previous"],
    style: "solid",
  },
  "balance-scale": {
    unicode: "",
    tags: [],
    style: "solid",
  },
  barcode: {
    unicode: "",
    tags: ["scan"],
    style: "solid",
  },
  "battery-empty": {
    unicode: "",
    tags: ["power", "status"],
    style: "solid",
  },
  "battery-full": {
    unicode: "",
    tags: ["power", "status"],
    style: "solid",
  },
  bell: {
    unicode: "",
    tags: ["alert", "reminder", "notification"],
    style: "solid",
  },
  "bell-slash": {
    unicode: "",
    tags: [],
    style: "solid",
  },
  binoculars: {
    unicode: "",
    tags: [],
    style: "solid",
  },
  bitbucket: {
    unicode: "",
    tags: ["git", "bitbucket-square"],
    style: "brands",
  },
  bitcoin: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  blackberry: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  bluetooth: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  bolt: {
    unicode: "",
    tags: ["lightning", "weather"],
    style: "solid",
  },
  bomb: {
    unicode: "",
    tags: [],
    style: "solid",
  },
  book: {
    unicode: "",
    tags: ["read", "documentation"],
    style: "solid",
  },
  bookmark: {
    unicode: "",
    tags: ["save"],
    style: "solid",
  },
  box: {
    unicode: "",
    tags: ["package"],
    style: "solid",
  },
  "box-open": {
    unicode: "",
    tags: [],
    style: "solid",
  },
  boxes: {
    unicode: "",
    tags: [],
    style: "solid",
  },
  briefcase: {
    unicode: "",
    tags: ["work", "business", "office", "luggage", "bag"],
    style: "solid",
  },
  btc: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  bug: {
    unicode: "",
    tags: ["report", "insect"],
    style: "solid",
  },
  building: {
    unicode: "",
    tags: ["work", "business", "apartment", "office", "company"],
    style: "solid",
  },
  bullhorn: {
    unicode: "",
    tags: ["announcement", "share", "broadcast", "louder", "megaphone"],
    style: "solid",
  },
  bullseye: {
    unicode: "",
    tags: ["target"],
    style: "solid",
  },
  burn: {
    unicode: "",
    tags: ["energy"],
    style: "solid",
  },
  calculator: {
    unicode: "",
    tags: [],
    style: "solid",
  },
  calendar: {
    unicode: "",
    tags: ["date", "time", "when", "event", "calendar-o", "schedule"],
    style: "solid",
  },
  camera: {
    unicode: "",
    tags: ["photo", "picture", "record"],
    style: "solid",
  },
  "caret-down": {
    unicode: "",
    tags: ["more", "dropdown", "menu", "triangle down", "arrow"],
    style: "solid",
  },
  "caret-left": {
    unicode: "",
    tags: ["previous", "back", "triangle left", "arrow"],
    style: "solid",
  },
  "caret-right": {
    unicode: "",
    tags: ["next", "forward", "triangle right", "arrow"],
    style: "solid",
  },
  "caret-square-down": {
    unicode: "",
    tags: ["more", "dropdown", "menu", "caret-square-o-down"],
    style: "solid",
  },
  "caret-square-left": {
    unicode: "",
    tags: ["previous", "back", "caret-square-o-left"],
    style: "solid",
  },
  "caret-square-right": {
    unicode: "",
    tags: ["next", "forward", "caret-square-o-right"],
    style: "solid",
  },
  "caret-square-up": {
    unicode: "",
    tags: ["caret-square-o-up"],
    style: "solid",
  },
  "caret-up": {
    unicode: "",
    tags: ["triangle up", "arrow"],
    style: "solid",
  },
  "cart-arrow-down": {
    unicode: "",
    tags: ["shopping"],
    style: "solid",
  },
  "cart-plus": {
    unicode: "",
    tags: ["add", "shopping"],
    style: "solid",
  },
  "cc-amazon-pay": {
    unicode: "",
    tags: [],
    style: "brands",
  },
  "cc-amex": {
    unicode: "",
    tags: ["amex"],
    style: "brands",
  },
  "cc-apple-pay": {
    unicode: "",
    tags: [],
    style: "brands",
  },
  "cc-diners-club": {
    unicode: "",
    tags: [],
    style: "brands",
  },
  "cc-discover": {
    unicode: "",
    tags: [],
    style: "brands",
  },
  "cc-jcb": {
    unicode: "",
    tags: [],
    style: "brands",
  },
  "cc-mastercard": {
    unicode: "",
    tags: [],
    style: "brands",
  },
  "cc-paypal": {
    unicode: "",
    tags: [],
    style: "brands",
  },
  "cc-stripe": {
    unicode: "",
    tags: [],
    style: "brands",
  },
  "cc-visa": {
    unicode: "",
    tags: [],
    style: "brands",
  },
  certificate: {
    unicode: "",
    tags: ["badge", "star"],
    style: "solid",
  },
  "chart-area": {
    unicode: "",
    tags: ["graph", "analytics", "area-chart"],
    style: "solid",
  },
  "chart-bar": {
    unicode: "",
    tags: ["graph", "analytics", "bar-chart"],
    style: "solid",
  },
  "chart-line": {
    unicode: "",
    tags: ["graph", "analytics", "line-chart", "dashboard"],
    style: "solid",
  },
  "chart-pie": {
    unicode: "",
    tags: ["graph", "analytics", "pie-chart"],
    style: "solid",
  },
  check: {
    unicode: "",
    tags: [
      "checkmark",
      "done",
      "todo",
      "agree",
      "accept",
      "confirm",
      "tick",
      "ok",
      "select",
      "success",
      "notification",
      "notify",
      "notice",
      "yes",
      "correct",
    ],
    style: "solid",
  },
  "check-circle": {
    unicode: "",
    tags: [
      "todo",
      "done",
      "agree",
      "accept",
      "confirm",
      "ok",
      "select",
      "success",
      "yes",
      "correct",
    ],
    style: "solid",
  },
  "check-square": {
    unicode: "",
    tags: [
      "checkmark",
      "done",
      "todo",
      "agree",
      "accept",
      "confirm",
      "ok",
      "select",
      "success",
      "yes",
      "correct",
    ],
    style: "solid",
  },
  "chevron-circle-down": {
    unicode: "",
    tags: ["more", "dropdown", "menu", "arrow"],
    style: "solid",
  },
  "chevron-circle-left": {
    unicode: "",
    tags: ["previous", "back", "arrow"],
    style: "solid",
  },
  "chevron-circle-right": {
    unicode: "",
    tags: ["next", "forward", "arrow"],
    style: "solid",
  },
  "chevron-circle-up": {
    unicode: "",
    tags: ["arrow"],
    style: "solid",
  },
  "chevron-down": {
    unicode: "",
    tags: [],
    style: "solid",
  },
  "chevron-left": {
    unicode: "",
    tags: ["bracket", "previous", "back"],
    style: "solid",
  },
  "chevron-right": {
    unicode: "",
    tags: ["bracket", "next", "forward"],
    style: "solid",
  },
  "chevron-up": {
    unicode: "",
    tags: [],
    style: "solid",
  },
  child: {
    unicode: "",
    tags: [],
    style: "solid",
  },
  chrome: {
    unicode: "",
    tags: ["browser"],
    style: "brands",
  },
  circle: {
    unicode: "",
    tags: ["dot", "notification", "circle-thin"],
    style: "solid",
  },
  "circle-notch": {
    unicode: "",
    tags: ["circle-o-notch"],
    style: "solid",
  },
  clipboard: {
    unicode: "",
    tags: ["paste"],
    style: "solid",
  },
  "clipboard-check": {
    unicode: "",
    tags: [
      "todo",
      "done",
      "agree",
      "accept",
      "confirm",
      "ok",
      "select",
      "success",
      "yes",
    ],
    style: "solid",
  },
  "clipboard-list": {
    unicode: "",
    tags: [
      "todo",
      "ul",
      "ol",
      "checklist",
      "finished",
      "completed",
      "done",
      "schedule",
      "intinerary",
    ],
    style: "solid",
  },
  clock: {
    unicode: "",
    tags: ["watch", "timer", "late", "timestamp", "date", "schedule"],
    style: "solid",
  },
  clone: {
    unicode: "",
    tags: ["copy"],
    style: "solid",
  },
  cloud: {
    unicode: "",
    tags: ["save"],
    style: "solid",
  },
  "cloud-download-alt": {
    unicode: "",
    tags: ["cloud-download"],
    style: "solid",
  },
  "cloud-upload-alt": {
    unicode: "",
    tags: ["cloud-upload"],
    style: "solid",
  },
  cloudscale: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  cloudsmith: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  cloudversify: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  code: {
    unicode: "",
    tags: ["html", "brackets"],
    style: "solid",
  },
  "code-branch": {
    unicode: "",
    tags: [
      "git",
      "fork",
      "vcs",
      "svn",
      "github",
      "rebase",
      "version",
      "branch",
      "code-fork",
    ],
    style: "solid",
  },
  codepen: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  coffee: {
    unicode: "",
    tags: ["morning", "mug", "breakfast", "tea", "drink", "cafe"],
    style: "solid",
  },
  cog: {
    unicode: "",
    tags: ["settings"],
    style: "solid",
  },
  cogs: {
    unicode: "",
    tags: ["settings", "gears"],
    style: "solid",
  },
  comment: {
    unicode: "",
    tags: [
      "speech",
      "notification",
      "note",
      "chat",
      "bubble",
      "feedback",
      "message",
      "texting",
      "sms",
      "conversation",
    ],
    style: "solid",
  },
  "comment-alt": {
    unicode: "",
    tags: [
      "speech",
      "notification",
      "note",
      "chat",
      "bubble",
      "feedback",
      "message",
      "texting",
      "sms",
      "conversation",
      "commenting",
      "commenting",
    ],
    style: "solid",
  },
  "comment-dots": {
    unicode: "",
    tags: [],
    style: "solid",
  },
  "comment-slash": {
    unicode: "",
    tags: [],
    style: "solid",
  },
  comments: {
    unicode: "",
    tags: [
      "speech",
      "notification",
      "note",
      "chat",
      "bubble",
      "feedback",
      "message",
      "texting",
      "sms",
      "conversation",
    ],
    style: "solid",
  },
  compass: {
    unicode: "",
    tags: ["safari", "directory", "menu", "location"],
    style: "solid",
  },
  compress: {
    unicode: "",
    tags: ["collapse", "combine", "contract", "merge", "smaller"],
    style: "solid",
  },
  copy: {
    unicode: "",
    tags: ["duplicate", "clone", "file", "files-o"],
    style: "solid",
  },
  copyright: {
    unicode: "",
    tags: [],
    style: "solid",
  },
  "credit-card": {
    unicode: "",
    tags: [
      "money",
      "buy",
      "debit",
      "checkout",
      "purchase",
      "payment",
      "credit-card-alt",
    ],
    style: "solid",
  },
  css3: {
    unicode: "",
    tags: ["code"],
    style: "brands",
  },
  cube: {
    unicode: "",
    tags: ["package"],
    style: "solid",
  },
  cubes: {
    unicode: "",
    tags: ["packages"],
    style: "solid",
  },
  cut: {
    unicode: "",
    tags: ["scissors", "scissors"],
    style: "solid",
  },
  database: {
    unicode: "",
    tags: [],
    style: "solid",
  },
  "digital-ocean": {
    unicode: "",
    tags: [],
    style: "brands",
  },
  docker: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  "dollar-sign": {
    unicode: "",
    tags: ["usd", "price"],
    style: "solid",
  },
  dolly: {
    unicode: "",
    tags: [],
    style: "solid",
  },
  "dolly-flatbed": {
    unicode: "",
    tags: [],
    style: "solid",
  },
  donate: {
    unicode: "",
    tags: ["give", "generosity"],
    style: "solid",
  },
  "dot-circle": {
    unicode: "",
    tags: ["target", "bullseye", "notification"],
    style: "solid",
  },
  download: {
    unicode: "",
    tags: ["import"],
    style: "solid",
  },
  dropbox: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  drupal: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  ember: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  envelope: {
    unicode: "",
    tags: [
      "email",
      "e-mail",
      "letter",
      "support",
      "mail",
      "message",
      "notification",
    ],
    style: "solid",
  },
  erlang: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  ethereum: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  "euro-sign": {
    unicode: "",
    tags: ["eur", "eur"],
    style: "solid",
  },
  "exchange-alt": {
    unicode: "",
    tags: [
      "transfer",
      "arrows",
      "arrow",
      "exchange",
      "swap",
      "return",
      "reciprocate",
    ],
    style: "solid",
  },
  exclamation: {
    unicode: "",
    tags: [
      "warning",
      "error",
      "problem",
      "notification",
      "notify",
      "notice",
      "alert",
      "danger",
    ],
    style: "solid",
  },
  "exclamation-circle": {
    unicode: "",
    tags: [
      "warning",
      "error",
      "problem",
      "notification",
      "notify",
      "notice",
      "alert",
      "danger",
    ],
    style: "solid",
  },
  "exclamation-triangle": {
    unicode: "",
    tags: [
      "warning",
      "error",
      "problem",
      "notification",
      "notify",
      "notice",
      "alert",
      "danger",
    ],
    style: "solid",
  },
  expand: {
    unicode: "",
    tags: ["enlarge", "bigger", "resize"],
    style: "solid",
  },
  "expand-arrows-alt": {
    unicode: "",
    tags: ["enlarge", "bigger", "resize", "move", "arrows-alt"],
    style: "solid",
  },
  expeditedssl: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  "external-link-alt": {
    unicode: "",
    tags: ["open", "new", "external-link"],
    style: "solid",
  },
  eye: {
    unicode: "",
    tags: ["show", "visible", "views", "see", "seen", "sight", "optic"],
    style: "solid",
  },
  "eye-dropper": {
    unicode: "",
    tags: ["eyedropper"],
    style: "solid",
  },
  "eye-slash": {
    unicode: "",
    tags: [
      "toggle",
      "show",
      "hide",
      "visible",
      "visiblity",
      "views",
      "unseen",
      "blind",
    ],
    style: "solid",
  },
  facebook: {
    unicode: "",
    tags: ["social network", "facebook-official"],
    style: "brands",
  },
  "facebook-messenger": {
    unicode: "",
    tags: [],
    style: "brands",
  },
  "fast-backward": {
    unicode: "",
    tags: ["rewind", "previous", "beginning", "start", "first"],
    style: "solid",
  },
  "fast-forward": {
    unicode: "",
    tags: ["next", "end", "last"],
    style: "solid",
  },
  fax: {
    unicode: "",
    tags: [],
    style: "solid",
  },
  female: {
    unicode: "",
    tags: ["woman", "human", "user", "person", "profile"],
    style: "solid",
  },
  file: {
    unicode: "",
    tags: ["new", "page", "pdf", "document"],
    style: "solid",
  },
  "file-alt": {
    unicode: "",
    tags: ["new", "page", "pdf", "document", "file-text", "invoice"],
    style: "solid",
  },
  "file-archive": {
    unicode: "",
    tags: ["zip", ".zip", "compress", "compression", "bundle", "download"],
    style: "solid",
  },
  "file-audio": {
    unicode: "",
    tags: [],
    style: "solid",
  },
  "file-code": {
    unicode: "",
    tags: [],
    style: "solid",
  },
  "file-excel": {
    unicode: "",
    tags: [],
    style: "solid",
  },
  "file-image": {
    unicode: "",
    tags: [],
    style: "solid",
  },
  "file-medical": {
    unicode: "",
    tags: [],
    style: "solid",
  },
  "file-medical-alt": {
    unicode: "",
    tags: [],
    style: "solid",
  },
  "file-pdf": {
    unicode: "",
    tags: [],
    style: "solid",
  },
  "file-powerpoint": {
    unicode: "",
    tags: [],
    style: "solid",
  },
  "file-video": {
    unicode: "",
    tags: [],
    style: "solid",
  },
  "file-word": {
    unicode: "",
    tags: [],
    style: "solid",
  },
  film: {
    unicode: "",
    tags: ["movie"],
    style: "solid",
  },
  filter: {
    unicode: "",
    tags: ["funnel", "options"],
    style: "solid",
  },
  fire: {
    unicode: "",
    tags: ["flame", "hot", "popular"],
    style: "solid",
  },
  firefox: {
    unicode: "",
    tags: ["browser"],
    style: "brands",
  },
  folder: {
    unicode: "",
    tags: [],
    style: "solid",
  },
  "folder-open": {
    unicode: "",
    tags: [],
    style: "solid",
  },
  forward: {
    unicode: "",
    tags: ["forward", "next"],
    style: "solid",
  },
  gamepad: {
    unicode: "",
    tags: ["controller"],
    style: "solid",
  },
  git: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  "git-square": {
    unicode: "",
    tags: [],
    style: "brands",
  },
  github: {
    unicode: "",
    tags: ["octocat"],
    style: "brands",
  },
  "github-alt": {
    unicode: "",
    tags: ["octocat"],
    style: "brands",
  },
  "github-square": {
    unicode: "",
    tags: ["octocat"],
    style: "brands",
  },
  gitkraken: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  gitlab: {
    unicode: "",
    tags: ["Axosoft"],
    style: "brands",
  },
  gitter: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  globe: {
    unicode: "",
    tags: [
      "world",
      "planet",
      "map",
      "place",
      "travel",
      "earth",
      "global",
      "translate",
      "all",
      "language",
      "localize",
      "location",
      "coordinates",
      "country",
      "gps",
      "online",
    ],
    style: "solid",
  },
  google: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  "google-drive": {
    unicode: "",
    tags: [],
    style: "brands",
  },
  "google-play": {
    unicode: "",
    tags: [],
    style: "brands",
  },
  "google-plus": {
    unicode: "",
    tags: ["google-plus-circle", "google-plus-official"],
    style: "brands",
  },
  "google-plus-g": {
    unicode: "",
    tags: ["social network", "google-plus"],
    style: "brands",
  },
  "google-plus-square": {
    unicode: "",
    tags: ["social network"],
    style: "brands",
  },
  "google-wallet": {
    unicode: "",
    tags: [],
    style: "brands",
  },
  "graduation-cap": {
    unicode: "",
    tags: ["learning", "school", "student"],
    style: "solid",
  },
  grunt: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  gulp: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  "hacker-news": {
    unicode: "",
    tags: [],
    style: "brands",
  },
  "hacker-news-square": {
    unicode: "",
    tags: [],
    style: "brands",
  },
  hashtag: {
    unicode: "",
    tags: [],
    style: "solid",
  },
  hdd: {
    unicode: "",
    tags: ["harddrive", "hard drive", "storage", "save", "machine"],
    style: "solid",
  },
  heading: {
    unicode: "",
    tags: ["header", "header"],
    style: "solid",
  },
  headphones: {
    unicode: "",
    tags: ["sound", "listen", "music", "audio", "speaker"],
    style: "solid",
  },
  heart: {
    unicode: "",
    tags: ["love", "like", "favorite"],
    style: "solid",
  },
  history: {
    unicode: "",
    tags: [],
    style: "solid",
  },
  home: {
    unicode: "",
    tags: ["main", "house"],
    style: "solid",
  },
  hourglass: {
    unicode: "",
    tags: [],
    style: "solid",
  },
  html5: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  "id-badge": {
    unicode: "",
    tags: [],
    style: "solid",
  },
  "id-card": {
    unicode: "",
    tags: [],
    style: "solid",
  },
  "id-card-alt": {
    unicode: "",
    tags: ["demographics"],
    style: "solid",
  },
  image: {
    unicode: "",
    tags: ["photo", "album", "picture", "picture"],
    style: "solid",
  },
  images: {
    unicode: "",
    tags: ["photo", "album", "picture"],
    style: "solid",
  },
  inbox: {
    unicode: "",
    tags: [],
    style: "solid",
  },
  industry: {
    unicode: "",
    tags: ["factory", "manufacturing"],
    style: "solid",
  },
  info: {
    unicode: "",
    tags: ["help", "information", "more", "details"],
    style: "solid",
  },
  "info-circle": {
    unicode: "",
    tags: ["help", "information", "more", "details"],
    style: "solid",
  },
  instagram: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  "internet-explorer": {
    unicode: "",
    tags: ["browser", "ie"],
    style: "brands",
  },
  ioxhost: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  itunes: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  java: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  jenkins: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  joomla: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  js: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  "js-square": {
    unicode: "",
    tags: [],
    style: "brands",
  },
  jsfiddle: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  key: {
    unicode: "",
    tags: ["unlock", "password"],
    style: "solid",
  },
  keyboard: {
    unicode: "",
    tags: ["type", "input"],
    style: "solid",
  },
  language: {
    unicode: "",
    tags: [],
    style: "solid",
  },
  laptop: {
    unicode: "",
    tags: [
      "demo",
      "computer",
      "device",
      "pc",
      "mac",
      "pc",
      "macbook",
      "dell",
      "dude you're getting",
      "machine",
    ],
    style: "solid",
  },
  laravel: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  less: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  "level-down-alt": {
    unicode: "",
    tags: ["level-down"],
    style: "solid",
  },
  "level-up-alt": {
    unicode: "",
    tags: ["level-up"],
    style: "solid",
  },
  "life-ring": {
    unicode: "",
    tags: ["support"],
    style: "solid",
  },
  lightbulb: {
    unicode: "",
    tags: ["idea", "inspiration"],
    style: "solid",
  },
  line: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  link: {
    unicode: "",
    tags: ["chain"],
    style: "solid",
  },
  linkedin: {
    unicode: "",
    tags: ["linkedin-square"],
    style: "brands",
  },
  linode: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  linux: {
    unicode: "",
    tags: ["tux"],
    style: "brands",
  },
  "lira-sign": {
    unicode: "",
    tags: ["try", "turkish", "try"],
    style: "solid",
  },
  "location-arrow": {
    unicode: "",
    tags: [
      "map",
      "coordinates",
      "location",
      "address",
      "place",
      "where",
      "gps",
    ],
    style: "solid",
  },
  lock: {
    unicode: "",
    tags: ["protect", "admin", "security"],
    style: "solid",
  },
  "lock-open": {
    unicode: "",
    tags: ["protect", "admin", "password", "lock", "open"],
    style: "solid",
  },
  magento: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  magic: {
    unicode: "",
    tags: ["wizard", "automatic", "autocomplete"],
    style: "solid",
  },
  magnet: {
    unicode: "",
    tags: [],
    style: "solid",
  },
  male: {
    unicode: "",
    tags: ["man", "human", "user", "person", "profile"],
    style: "solid",
  },
  map: {
    unicode: "",
    tags: [],
    style: "solid",
  },
  maxcdn: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  medium: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  medkit: {
    unicode: "",
    tags: ["first aid", "firstaid", "help", "support", "health"],
    style: "solid",
  },
  medrt: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  meetup: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  meh: {
    unicode: "",
    tags: ["face", "emoticon", "rating", "neutral"],
    style: "solid",
  },
  mercury: {
    unicode: "",
    tags: ["transgender"],
    style: "solid",
  },
  microchip: {
    unicode: "",
    tags: [],
    style: "solid",
  },
  microphone: {
    unicode: "",
    tags: ["record", "voice", "sound"],
    style: "solid",
  },
  "microphone-slash": {
    unicode: "",
    tags: ["record", "voice", "sound", "mute"],
    style: "solid",
  },
  microsoft: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  minus: {
    unicode: "",
    tags: ["hide", "minify", "delete", "remove", "trash", "hide", "collapse"],
    style: "solid",
  },
  mobile: {
    unicode: "",
    tags: [
      "cell phone",
      "cellphone",
      "text",
      "call",
      "number",
      "telephone",
      "device",
      "screen",
      "apple",
      "iphone",
    ],
    style: "solid",
  },
  "mobile-alt": {
    unicode: "",
    tags: [
      "cell phone",
      "cellphone",
      "text",
      "call",
      "number",
      "telephone",
      "device",
      "screen",
      "apple",
      "iphone",
    ],
    style: "solid",
  },
  "money-bill-alt": {
    unicode: "",
    tags: ["cash", "money", "buy", "checkout", "purchase", "payment", "price"],
    style: "solid",
  },
  moon: {
    unicode: "",
    tags: ["night", "darker", "contrast"],
    style: "solid",
  },
  "mouse-pointer": {
    unicode: "",
    tags: ["select"],
    style: "solid",
  },
  music: {
    unicode: "",
    tags: ["note", "sound"],
    style: "solid",
  },
  newspaper: {
    unicode: "",
    tags: ["press", "article"],
    style: "solid",
  },
  node: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  "node-js": {
    unicode: "",
    tags: [],
    style: "brands",
  },
  npm: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  opencart: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  openid: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  opera: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  "paper-plane": {
    unicode: "",
    tags: [],
    style: "solid",
  },
  paperclip: {
    unicode: "",
    tags: ["attachment"],
    style: "solid",
  },
  "parachute-box": {
    unicode: "",
    tags: ["aid", "assistance", "rescue", "supplies"],
    style: "solid",
  },
  pause: {
    unicode: "",
    tags: ["wait"],
    style: "solid",
  },
  paypal: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  "pen-square": {
    unicode: "",
    tags: ["write", "edit", "update", "pencil-square"],
    style: "solid",
  },
  "pencil-alt": {
    unicode: "",
    tags: ["write", "edit", "update", "pencil", "design"],
    style: "solid",
  },
  percent: {
    unicode: "",
    tags: [],
    style: "solid",
  },
  "phoenix-framework": {
    unicode: "",
    tags: [],
    style: "brands",
  },
  phone: {
    unicode: "",
    tags: ["call", "voice", "number", "support", "earphone", "telephone"],
    style: "solid",
  },
  php: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  "piggy-bank": {
    unicode: "",
    tags: ["savings", "save"],
    style: "solid",
  },
  pills: {
    unicode: "",
    tags: ["medicine", "drugs"],
    style: "solid",
  },
  pinterest: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  plane: {
    unicode: "",
    tags: [
      "travel",
      "trip",
      "location",
      "destination",
      "airplane",
      "fly",
      "mode",
    ],
    style: "solid",
  },
  playstation: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  plug: {
    unicode: "",
    tags: ["power", "connect", "online"],
    style: "solid",
  },
  plus: {
    unicode: "",
    tags: ["add", "new", "create", "expand"],
    style: "solid",
  },
  podcast: {
    unicode: "",
    tags: [],
    style: "solid",
  },
  poo: {
    unicode: "",
    tags: [],
    style: "solid",
  },
  "pound-sign": {
    unicode: "",
    tags: ["gbp", "gbp"],
    style: "solid",
  },
  "power-off": {
    unicode: "",
    tags: ["on"],
    style: "solid",
  },
  print: {
    unicode: "",
    tags: [],
    style: "solid",
  },
  "product-hunt": {
    unicode: "",
    tags: [],
    style: "brands",
  },
  pushed: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  "puzzle-piece": {
    unicode: "",
    tags: ["addon", "add-on", "section"],
    style: "solid",
  },
  python: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  qq: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  qrcode: {
    unicode: "",
    tags: ["scan"],
    style: "solid",
  },
  question: {
    unicode: "",
    tags: ["help", "information", "unknown", "support"],
    style: "solid",
  },
  "question-circle": {
    unicode: "",
    tags: ["help", "information", "unknown", "support"],
    style: "solid",
  },
  quora: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  random: {
    unicode: "",
    tags: ["sort", "shuffle"],
    style: "solid",
  },
  react: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  readme: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  recycle: {
    unicode: "",
    tags: [],
    style: "solid",
  },
  reddit: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  redo: {
    unicode: "",
    tags: ["forward", "repeat", "repeat"],
    style: "solid",
  },
  registered: {
    unicode: "",
    tags: [],
    style: "solid",
  },
  resolving: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  retweet: {
    unicode: "",
    tags: ["refresh", "reload", "share", "swap"],
    style: "solid",
  },
  ribbon: {
    unicode: "",
    tags: ["cause", "badge", "pin", "lapel"],
    style: "solid",
  },
  road: {
    unicode: "",
    tags: ["street"],
    style: "solid",
  },
  rocket: {
    unicode: "",
    tags: ["app"],
    style: "solid",
  },
  rss: {
    unicode: "",
    tags: ["blog"],
    style: "solid",
  },
  "ruble-sign": {
    unicode: "",
    tags: ["rub", "rub"],
    style: "solid",
  },
  "rupee-sign": {
    unicode: "",
    tags: ["indian", "inr"],
    style: "solid",
  },
  safari: {
    unicode: "",
    tags: ["browser"],
    style: "brands",
  },
  sass: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  save: {
    unicode: "",
    tags: ["floppy", "floppy-o"],
    style: "solid",
  },
  search: {
    unicode: "",
    tags: ["magnify", "zoom", "enlarge", "bigger", "preview"],
    style: "solid",
  },
  "search-minus": {
    unicode: "",
    tags: ["magnify", "minify", "zoom", "smaller", "zoom out"],
    style: "solid",
  },
  "search-plus": {
    unicode: "",
    tags: ["magnify", "zoom", "enlarge", "bigger", "zoom in"],
    style: "solid",
  },
  searchengin: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  server: {
    unicode: "",
    tags: [],
    style: "solid",
  },
  share: {
    unicode: "",
    tags: [],
    style: "solid",
  },
  "shekel-sign": {
    unicode: "",
    tags: ["ils", "ils"],
    style: "solid",
  },
  "shield-alt": {
    unicode: "",
    tags: ["shield"],
    style: "solid",
  },
  ship: {
    unicode: "",
    tags: ["boat", "sea"],
    style: "solid",
  },
  "shipping-fast": {
    unicode: "",
    tags: [],
    style: "solid",
  },
  "shopping-bag": {
    unicode: "",
    tags: [],
    style: "solid",
  },
  "shopping-basket": {
    unicode: "",
    tags: [],
    style: "solid",
  },
  "shopping-cart": {
    unicode: "",
    tags: ["checkout", "buy", "purchase", "payment"],
    style: "solid",
  },
  shower: {
    unicode: "",
    tags: [],
    style: "solid",
  },
  sign: {
    unicode: "",
    tags: [],
    style: "solid",
  },
  signal: {
    unicode: "",
    tags: ["graph", "bars", "status", "online"],
    style: "solid",
  },
  skype: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  slack: {
    unicode: "",
    tags: ["hashtag", "anchor", "hash"],
    style: "brands",
  },
  "slack-hash": {
    unicode: "",
    tags: ["hashtag", "anchor", "hash"],
    style: "brands",
  },
  "sliders-h": {
    unicode: "",
    tags: ["settings", "sliders"],
    style: "solid",
  },
  slideshare: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  smile: {
    unicode: "",
    tags: ["face", "emoticon", "happy", "approve", "satisfied", "rating"],
    style: "solid",
  },
  smoking: {
    unicode: "",
    tags: ["smoking status", "cigarette", "nicotine"],
    style: "solid",
  },
  snapchat: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  snowflake: {
    unicode: "",
    tags: [],
    style: "solid",
  },
  soundcloud: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  "space-shuttle": {
    unicode: "",
    tags: ["nasa", "astronaut", "rocket", "machine", "transportation"],
    style: "solid",
  },
  speakap: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  spinner: {
    unicode: "",
    tags: ["loading", "progress"],
    style: "solid",
  },
  spotify: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  square: {
    unicode: "",
    tags: ["block", "box"],
    style: "solid",
  },
  "square-full": {
    unicode: "",
    tags: [],
    style: "solid",
  },
  "stack-exchange": {
    unicode: "",
    tags: [],
    style: "brands",
  },
  "stack-overflow": {
    unicode: "",
    tags: [],
    style: "brands",
  },
  star: {
    unicode: "",
    tags: ["award", "achievement", "night", "rating", "score", "favorite"],
    style: "solid",
  },
  "star-half": {
    unicode: "",
    tags: [
      "award",
      "achievement",
      "rating",
      "score",
      "star-half-empty",
      "star-half-full",
    ],
    style: "solid",
  },
  staylinked: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  steam: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  "step-backward": {
    unicode: "",
    tags: ["rewind", "previous", "beginning", "start", "first"],
    style: "solid",
  },
  "step-forward": {
    unicode: "",
    tags: ["next", "end", "last"],
    style: "solid",
  },
  "sticky-note": {
    unicode: "",
    tags: [],
    style: "solid",
  },
  stop: {
    unicode: "",
    tags: ["block", "box", "square"],
    style: "solid",
  },
  "stop-circle": {
    unicode: "",
    tags: [],
    style: "solid",
  },
  stopwatch: {
    unicode: "",
    tags: ["time"],
    style: "solid",
  },
  strikethrough: {
    unicode: "",
    tags: [],
    style: "solid",
  },
  stripe: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  stumbleupon: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  suitcase: {
    unicode: "",
    tags: ["trip", "luggage", "travel", "move", "baggage"],
    style: "solid",
  },
  sun: {
    unicode: "",
    tags: ["weather", "contrast", "lighter", "brighten", "day"],
    style: "solid",
  },
  superpowers: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  sync: {
    unicode: "",
    tags: ["reload", "refresh", "exchange", "swap"],
    style: "solid",
  },
  "sync-alt": {
    unicode: "",
    tags: ["reload", "refresh"],
    style: "solid",
  },
  table: {
    unicode: "",
    tags: ["data", "excel", "spreadsheet"],
    style: "solid",
  },
  tablet: {
    unicode: "",
    tags: ["device", "screen", "apple", "ipad", "kindle"],
    style: "solid",
  },
  "tablet-alt": {
    unicode: "",
    tags: ["device", "screen", "apple", "ipad", "kindle"],
    style: "solid",
  },
  tablets: {
    unicode: "",
    tags: ["medicine", "drugs"],
    style: "solid",
  },
  "tachometer-alt": {
    unicode: "",
    tags: ["tachometer", "dashboard"],
    style: "solid",
  },
  tag: {
    unicode: "",
    tags: ["label"],
    style: "solid",
  },
  tags: {
    unicode: "",
    tags: ["labels"],
    style: "solid",
  },
  tape: {
    unicode: "",
    tags: [],
    style: "solid",
  },
  tasks: {
    unicode: "",
    tags: ["progress", "loading", "downloading", "downloads", "settings"],
    style: "solid",
  },
  taxi: {
    unicode: "",
    tags: [
      "vehicle",
      "machine",
      "transportation",
      "cab",
      "cabbie",
      "car",
      "uber",
      "lyft",
      "car service",
    ],
    style: "solid",
  },
  telegram: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  "telegram-plane": {
    unicode: "",
    tags: [],
    style: "brands",
  },
  "tencent-weibo": {
    unicode: "",
    tags: [],
    style: "brands",
  },
  terminal: {
    unicode: "",
    tags: ["command", "prompt", "code", "console"],
    style: "solid",
  },
  thermometer: {
    unicode: "",
    tags: ["temperature", "fever"],
    style: "solid",
  },
  "thumbs-down": {
    unicode: "",
    tags: ["dislike", "disapprove", "disagree", "hand", "thumbs-o-down"],
    style: "solid",
  },
  "thumbs-up": {
    unicode: "",
    tags: [
      "like",
      "favorite",
      "approve",
      "agree",
      "hand",
      "thumbs-o-up",
      "success",
      "yes",
      "ok",
      "okay",
      "you got it dude",
    ],
    style: "solid",
  },
  thumbtack: {
    unicode: "",
    tags: ["marker", "pin", "location", "coordinates", "thumb-tack"],
    style: "solid",
  },
  "ticket-alt": {
    unicode: "",
    tags: ["ticket"],
    style: "solid",
  },
  times: {
    unicode: "",
    tags: [
      "close",
      "exit",
      "x",
      "cross",
      "error",
      "problem",
      "notification",
      "notify",
      "notice",
      "wrong",
      "incorrect",
    ],
    style: "solid",
  },
  "times-circle": {
    unicode: "",
    tags: [
      "close",
      "exit",
      "x",
      "cross",
      "problem",
      "notification",
      "notify",
      "notice",
      "wrong",
      "incorrect",
    ],
    style: "solid",
  },
  tint: {
    unicode: "",
    tags: ["raindrop", "waterdrop", "drop", "droplet"],
    style: "solid",
  },
  "toggle-off": {
    unicode: "",
    tags: ["switch"],
    style: "solid",
  },
  "toggle-on": {
    unicode: "",
    tags: ["switch"],
    style: "solid",
  },
  trademark: {
    unicode: "",
    tags: [],
    style: "solid",
  },
  train: {
    unicode: "",
    tags: ["bullet", "locomotive", "railway"],
    style: "solid",
  },
  transgender: {
    unicode: "",
    tags: ["intersex"],
    style: "solid",
  },
  "transgender-alt": {
    unicode: "",
    tags: [],
    style: "solid",
  },
  trash: {
    unicode: "",
    tags: ["garbage", "delete", "remove", "hide"],
    style: "solid",
  },
  "trash-alt": {
    unicode: "",
    tags: ["garbage", "delete", "remove", "hide", "trash", "trash-o"],
    style: "solid",
  },
  tree: {
    unicode: "",
    tags: [],
    style: "solid",
  },
  trello: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  tripadvisor: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  trophy: {
    unicode: "",
    tags: ["award", "achievement", "cup", "winner", "game"],
    style: "solid",
  },
  truck: {
    unicode: "",
    tags: ["shipping", "delivery"],
    style: "solid",
  },
  "tumblr-square": {
    unicode: "",
    tags: [],
    style: "brands",
  },
  tv: {
    unicode: "",
    tags: ["display", "computer", "monitor", "television"],
    style: "solid",
  },
  twitch: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  twitter: {
    unicode: "",
    tags: ["tweet", "social network"],
    style: "brands",
  },
  typo3: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  uber: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  uikit: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  umbrella: {
    unicode: "",
    tags: [],
    style: "solid",
  },
  underline: {
    unicode: "",
    tags: [],
    style: "solid",
  },
  undo: {
    unicode: "",
    tags: ["back", "exchange", "swap", "return", "control z", "oops"],
    style: "solid",
  },
  university: {
    unicode: "",
    tags: ["bank", "institution"],
    style: "solid",
  },
  unlink: {
    unicode: "",
    tags: ["remove", "chain", "chain-broken"],
    style: "solid",
  },
  unlock: {
    unicode: "",
    tags: ["protect", "admin", "password", "lock"],
    style: "solid",
  },
  "unlock-alt": {
    unicode: "",
    tags: ["protect", "admin", "password", "lock"],
    style: "solid",
  },
  upload: {
    unicode: "",
    tags: ["import"],
    style: "solid",
  },
  usb: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  user: {
    unicode: "",
    tags: ["person", "man", "head", "profile", "account"],
    style: "solid",
  },
  "user-circle": {
    unicode: "",
    tags: ["person", "man", "head", "profile", "account"],
    style: "solid",
  },
  "user-md": {
    unicode: "",
    tags: ["doctor", "profile", "medical", "nurse", "job", "occupation"],
    style: "solid",
  },
  "user-plus": {
    unicode: "",
    tags: ["sign up", "signup"],
    style: "solid",
  },
  "user-secret": {
    unicode: "",
    tags: ["whisper", "spy", "incognito", "privacy"],
    style: "solid",
  },
  "user-times": {
    unicode: "",
    tags: [],
    style: "solid",
  },
  users: {
    unicode: "",
    tags: ["people", "profiles", "persons"],
    style: "solid",
  },
  video: {
    unicode: "",
    tags: ["film", "movie", "record", "camera", "video-camera"],
    style: "solid",
  },
  vimeo: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  vk: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  "volume-down": {
    unicode: "",
    tags: ["audio", "lower", "quieter", "sound", "music", "speaker"],
    style: "solid",
  },
  "volume-off": {
    unicode: "",
    tags: ["audio", "mute", "sound", "music"],
    style: "solid",
  },
  "volume-up": {
    unicode: "",
    tags: ["audio", "higher", "louder", "sound", "music", "speaker"],
    style: "solid",
  },
  vuejs: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  warehouse: {
    unicode: "",
    tags: [],
    style: "solid",
  },
  weibo: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  weight: {
    unicode: "",
    tags: ["scale"],
    style: "solid",
  },
  weixin: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  whatsapp: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  wheelchair: {
    unicode: "",
    tags: ["handicap", "person"],
    style: "solid",
  },
  wifi: {
    unicode: "",
    tags: [],
    style: "solid",
  },
  "wikipedia-w": {
    unicode: "",
    tags: [],
    style: "brands",
  },
  "window-close": {
    unicode: "",
    tags: [],
    style: "solid",
  },
  "window-maximize": {
    unicode: "",
    tags: [],
    style: "solid",
  },
  "window-minimize": {
    unicode: "",
    tags: [],
    style: "solid",
  },
  "window-restore": {
    unicode: "",
    tags: [],
    style: "solid",
  },
  windows: {
    unicode: "",
    tags: ["microsoft"],
    style: "brands",
  },
  "wine-glass": {
    unicode: "",
    tags: [],
    style: "solid",
  },
  "won-sign": {
    unicode: "",
    tags: ["krw", "krw"],
    style: "solid",
  },
  wordpress: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  wrench: {
    unicode: "",
    tags: ["settings", "fix", "update", "spanner", "tool"],
    style: "solid",
  },
  "x-ray": {
    unicode: "",
    tags: ["radiological images", "radiology"],
    style: "solid",
  },
  xbox: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  xing: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  "y-combinator": {
    unicode: "",
    tags: [],
    style: "brands",
  },
  yahoo: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  yandex: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  yelp: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  "yen-sign": {
    unicode: "",
    tags: ["jpy", "jpy"],
    style: "solid",
  },
  yoast: {
    unicode: "",
    tags: [],
    style: "brands",
  },
  youtube: {
    unicode: "",
    tags: ["video", "film", "youtube-play", "youtube-square"],
    style: "brands",
  },
};

export default ICONS;
